const SETSTRATEGYSTART = "SETSTRATEGYSTART";
const SETLEGS = "SETLEGS";
const SETLEGSLEVEL = "SETLEGSLEVEL";
const SET_STRATEGY_LIST_BY_BASKET_ID = "SET_STRATEGY_DETAILS_BY_BASKET_ID ";
const SET_STRATEGY_DETAILS_BY_STRATEGY_ID =
  "SET_STRATEGY_DETAILS_BY_STRATEGY_ID ";

export {
  SET_STRATEGY_LIST_BY_BASKET_ID,
  SET_STRATEGY_DETAILS_BY_STRATEGY_ID,
  SETLEGS,
  SETLEGSLEVEL,
  SETSTRATEGYSTART,
};
