# Generated by Django 4.2.1 on 2023-08-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algoTradingApp", "0005_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leg",
            name="reEntryOrReExecute",
            field=models.CharField(
                choices=[("RE_ENTRY", "RE_ENTRY"), ("RE_EXECUTE", "RE_EXECUTE")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="leg",
            name="spotOrFutures",
            field=models.CharField(
                choices=[("SPOT", "SPOT"), ("FUTURES", "FUTURES")], max_length=20
            ),
        ),
    ]
