# Generated by Django 4.2.1 on 2023-09-20 01:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("algoTradingApp", "0006_alter_leg_reentryorreexecute_alter_leg_spotorfutures"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leg",
            name="reEntryOrReExecute",
        ),
        migrations.RemoveField(
            model_name="leg",
            name="spotOrFutures",
        ),
        migrations.AddField(
            model_name="strategy",
            name="strategyLongDescription",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="strategy",
            name="strategyShortDescription",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="legcondition",
            name="legConditionType",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="strategycondition",
            name="conditionType",
            field=models.CharField(max_length=50),
        ),
    ]
